#!/usr/bin/env bash

# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx

# Create a simple Hello World index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure a rewrite rule for redirection
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page for 404 errors
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
