#!/usr/bin/env bash
#a Bash script that displays Best School 10 times.using while loop 
counter="1"
display="Best School"
while [ $counter -le 10 ]
    do
        echo $display
        ((counter++))
    done