#!/usr/bin/env bash

# Check for root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root or using sudo."
    exit 1
fi

# Update package information and install ufw
sudo apt-get -y update
sudo apt-get -y install ufw

# Disable ufw
sudo ufw disable

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific TCP ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable
